### PR TITLE
gRPC network kv-memstore example

### PR DESCRIPTION
**Pull request by sainad2222**
Related to https://github.com/databendlabs/openraft/issues/1271 and https://github.com/databendlabs/openraft/issues/161

- - -
This change is [Reviewable](https://reviewable.io/reviews/databendlabs/openraft/1274)

### CODE REVIEW

**Review by drmingdrmer — COMMENTED** [review]
> Reviewed 7 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/databendlabs/openraft/1274)* status: 7 of 18 files reviewed, 8 unresolved discussions (waiting on @sainad2222)

___
*[`examples/raft-kv-memstore-grpc/proto/internal_service.proto` line 7 at r1](https://reviewable.io/reviews/databendlabs/openraft/1274#-ODiQiJh5r53lcGCrrNC:-ODiQiJh5r53lcGCrrND:bpch383) ([raw file](https://github.com/databendlabs/openraft/blob/59cab56754f1448c772a9dc1fd8be984c6668c20/examples/raft-kv-memstore-grpc/proto/internal_service.proto#L7)):*
> ```proto
> service InternalService {
>   // Vote handles vote requests between Raft nodes during leader election
>   rpc Vote(RaftRequestBytes) returns (RaftReplyBytes) {}
> ```

Although Vote RPC is not on the hot path, defining specific message types for its request and response better represents the voting protocol's semantics.
___
*[`examples/raft-kv-memstore-grpc/proto/internal_service.proto` line 10 at r1](https://reviewable.io/reviews/databendlabs/openraft/1274#-ODiRT43Ccq8Lrf9EOr1:-ODiRT43Ccq8Lrf9EOr2:b6ofdvz) ([raw file](https://github.com/databendlabs/openraft/blob/59cab56754f1448c772a9dc1fd8be984c6668c20/examples/raft-kv-memstore-grpc/proto/internal_service.proto#L10)):*
> ```proto
> 
>   // Append handles call related to append entries RPC
>   rpc Append(RaftRequestBytes) returns (RaftReplyBytes) {}
> ```

AppendEntries is on the hot path. To avoid double encoding/decoding, the request should be defined with a protobuf message instead of a general serialized bytes wrapper.
___
*[`examples/raft-kv-memstore-grpc/proto/internal_service.proto` line 13 at r1](https://reviewable.io/reviews/databendlabs/openraft/1274#-ODiRsRYCHJcnqBXJo8m:-ODiRsRYCHJcnqBXJo8n:btcy8lb) ([raw file](https://github.com/databendlabs/openraft/blob/59cab56754f1448c772a9dc1fd8be984c6668c20/examples/raft-kv-memstore-grpc/proto/internal_service.proto#L13)):*
> ```proto
> 
>   // Snapshot handles install snapshot RPC
>   rpc Snapshot(RaftRequestBytes) returns (RaftReplyBytes) {}
> ```

Snapshot is recommended to be transfer via a stream, refer to:
https://github.com/datafuselabs/databend/blob/22a8a82bc3fd532988ed661084eeeb1ef3bf3066/src/meta/types/proto/meta.proto#L273

And using `RaftNetworkV2` is recommended. See below.
___
*[`examples/raft-kv-memstore-grpc/src/lib.rs` line 21 at r1](https://reviewable.io/reviews/databendlabs/openraft/1274#-ODigBUKDpeULrK63vIv:-ODigBUKDpeULrK63vIw:byw3ur7) ([raw file](https://github.com/databendlabs/openraft/blob/59cab56754f1448c772a9dc1fd8be984c6668c20/examples/raft-kv-memstore-grpc/src/lib.rs#L21)):*
> ```XML
>         D = Request,
>         R = Response,
>         Node = Node,
> ```

`Entry` should be defined with protobuf too.
___
*[`examples/raft-kv-memstore-grpc/src/lib.rs` line 32 at r1](https://reviewable.io/reviews/databendlabs/openraft/1274#-ODigJei9mwTkmgSx6Uo:-ODigJei9mwTkmgSx6Up:b7ctrnz) ([raw file](https://github.com/databendlabs/openraft/blob/59cab56754f1448c772a9dc1fd8be984c6668c20/examples/raft-kv-memstore-grpc/src/lib.rs#L32)):*
> ```XML
>     pub node_id: u64,
>     pub rpc_addr: String,
> }
> ```

Use protobuf defined Node?



_Code quote:_
```XML
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize, PartialEq, Eq, Default)]
pub struct Node {
    pub node_id: u64,
    pub rpc_addr: String,
}
```
___
*[`examples/raft-kv-memstore-grpc/README.md` line 1 at r1](https://reviewable.io/reviews/databendlabs/openraft/1274#-ODiOmqn71sxciOGFwvn:-ODiOmqn71sxciOGFwvo:b-l26zkt) ([raw file](https://github.com/databendlabs/openraft/blob/59cab56754f1448c772a9dc1fd8be984c6668c20/examples/raft-kv-memstore-grpc/README.md#L1)):*
> ```Markdown
> # Example distributed key-value store built upon openraft.
> ```

This  README should be updated to reflect the purpose of the gRPC example.
___
*[`examples/raft-kv-memstore-grpc/src/network/mod.rs` line 62 at r1](https://reviewable.io/reviews/databendlabs/openraft/1274#-ODiSLZdEF_X5AKPjqBg:-ODiSLZdEF_X5AKPjqBh:b8n28bi) ([raw file](https://github.com/databendlabs/openraft/blob/59cab56754f1448c772a9dc1fd8be984c6668c20/examples/raft-kv-memstore-grpc/src/network/mod.rs#L62)):*
> ```XML
> /// Implementation of RaftNetwork trait for handling Raft protocol communications.
> #[allow(clippy::blocks_in_conditions)]
> impl RaftNetwork<TypeConfig> for NetworkConnection {
> ```

Implement RaftNetworkV2 instead of RaftNetwork. V2 provide a more generic snapshot API that allows user to customize the snapshot transmit.
___
*[`examples/raft-kv-memstore-grpc/proto/management_service.proto` line 33 at r1](https://reviewable.io/reviews/databendlabs/openraft/1274#-ODiT6EMDwXa_6vskJAL:-ODiT6EMDwXa_6vskJAM:b-lcmjfg) ([raw file](https://github.com/databendlabs/openraft/blob/59cab56754f1448c772a9dc1fd8be984c6668c20/examples/raft-kv-memstore-grpc/proto/management_service.proto#L33)):*
> ```proto
> message AddLearnerRequest {
>   Node node = 1;      // Node to be added as a learner
>   bool blocking = 2;  // Whether to wait for the operation to complete
> ```

As an example it does not have to exactly reflect the API and should be simplified if possible. We can assume in this example `add_learner` is always invoked in blocking mode and this argument is unnecessary. 

As a result, some of the **request** type may be removed. just use `Node` as the RPC request type.

**Comment by sainad2222** [comment]
> Entry should be defined with protobuf too.

Not sure how to convert all of entry to protobuf and it looks complex to convert with all the traits that we need to implement for that protobuf Entry. I looked for the reference in both `databend` repo and `robustmq` repo but couldn't find anything in both. Any references you can share or any pointers to get started?

> AppendEntries is on the hot path. To avoid double encoding/decoding, the request should be defined with a protobuf message instead of a general serialized bytes wrapper.

Same as above since request of this depends on Entry. Also wouldn't we writing a converter to convert from protobuf::AppendRequest to openraft::AppendEntriesRequest which also has some overhead? Will it be significantly better than serialization and deserialization?

**Comment by schreter** [comment]
> it looks complex to convert with all the traits that we need to implement for that protobuf Entry

I don't have a solution for you, but maybe a direction: You can add traits yourself. And, for instance, implement `AppendEntries` gRPC which consumes arbitrary entries fulfilling `where EntryType: ProvidesRpcEntry` or so and define a trait `ProvidesRpcEntry`, which will give you the entry directly as gRPC object, which you can then serialize 1:1 into `AppendEntries` w/o extra steps. This would require the application to use entries which implement the specified trait, but that's OK.

**Comment by drmingdrmer** [comment]
> > Entry should be defined with protobuf too.
> 
> Not sure how to convert all of entry to protobuf and it looks complex to convert with all the traits that we need to implement for that protobuf Entry. I looked for the reference in both `databend` repo and `robustmq` repo but couldn't find anything in both. Any references you can share or any pointers to get started?

You are right. 

Currently, `Entry` cannot be defined in protobuf because it depends on `LogId` and `Membership`, which are not part of the RaftTypeConfig trait.

I'll try to refactor the traits so that an `Entry` that does not depends on `LogId` and `Membership` can be introduced.

**Comment by sainad2222** [comment]
@drmingdrmer I made changes except for Entry and AppendEntries since it also depends on Entry. We can pick these two in a separate PR after your refactor. I used AI to make changes for snapshot function since I am new to streaming RPCs. Let me know if anything can be improved there

**Comment by sainad2222** [comment]
@drmingdrmer Resolved new comments too. You can review again

**Review by drmingdrmer — DISMISSED** [review]
Looks good enough

> Reviewed 12 of 12 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/databendlabs/openraft/1274#-:-ODzzsOCC4keKUoiaLJz:b2gg4le)* status: all files reviewed, 6 unresolved discussions (waiting on @sainad2222)

**Pull request merged**
